account/urls.py
from django.urls import path
from . import views


app_name = "account"


urlpatterns = [
    path("", views.account, name="account"),
    path("kyc-reg/", views.KycRegistration, name="kyc-reg"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('deposit/', views.deposit, name="deposit"),
    path('withdraw/', views.withdraw, name="withdraw")
]

core/urls.py
from django.urls import path
from . import views
from . import transfer
from . import transaction
from . import payment_requst
from . import credit_card

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('searchuser/', transfer.search_user_with_account_number, name="search-user"),
    path('amount-transfer/<accountNumber>/', transfer.AmonutTransfer, name="transfer"),
    path('amount-transfer-process/<account_number>/', transfer.AmountTransferProcess, name="transferprocess"),
    path('transfer-confirmation/<accountnumber>/<transaction_id>/', transfer.Transaction_confirmation, name="transferconfirmation"),
    path('transfer-completion-process/<accountnumber>/<transaction_id>/', transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<accountnumber>/<transaction_id>/", transfer.transfer_completed, name='transfer-completed'),
    path('transaction-list/', transaction.transaction_list, name="transaction-list"),
    path('transaction-detail/<transaction_id>/', transaction.transaction_detail, name="transaction-detail"),
    path('searchuserrequest/', payment_requst.searchUserRequest, name="searchuserrequest"),
    path("payment-request/<accountNumber>/", payment_requst.amountRequest, name="paymentrequest"),
    path('amount-request-process/<accountNumber>/', payment_requst.amountRequestProcess, name='amountrequestprocess'),
    path('request_confirmation/<accountNumber>/<transaction_id>/', payment_requst.requestConfirmation, name="requestconfirmation"),
    path('request_final_confirmation/<accountNumber>/<transaction_id>/', payment_requst.amoutnRequestFinalProcess, name="requestfinalconfirmation"),
    path('request-completed/<accountNumber>/<transaction_id>/', payment_requst.requestComplted, name='requestcompleted'),
    path('settlement_confirmation/<accountNumber>/<transaction_id>/', payment_requst.settlement_confirmation, name="settlementconfirmation"),
    path('settlementprocessing/<accountNumber>/<transaction_id>/', payment_requst.settlement_processing, name="settlementprocessing"),
    path('settlement-completed/<accountNumber>/<transaction_id>/', payment_requst.settlement_completed, name="settlementcompletd"),
    path('delete-request/<accountNumber>/<transaction_id>/', payment_requst.request_delete, name="requestdelete"),
    path('card/<card_id>/', credit_card.card_detail, name="creditcarddetail"),
    path('fundingcard/<card_id>/', credit_card.fund_credit_card, name="fundcreditcard"),
    path('withdrawfund/<card_id>/', credit_card.withdraw_fund, name="withdrawfund"),
    path("delete-credit-card/<card_id>/", credit_card.delete_card, name="deletecreditcard"),
    path('recipients/', transaction.recipient_list, name="recipients")

]

paymentProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('users/', include("userauth.urls")),
    path('account/', include("account.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from .import views

app_name = "userauth"

urlpatterns = [
    path("signup/", views.RegisterView, name="signup"),
    path("signin/", views.SignInView, name="signin"),
    path("signout/", views.SignOutView, name="signout"),
    path('reset/', views.password_reset, name="resetpassword")
]

templates/partials/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PayEstif - Money Transfer and Online Payments HTML Template</title>
    
    <link rel="shortcut icon" href="{% static 'assets/images/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    <a href="javascript:void(0)" class="scrollToTop"><i class="fas fa-angle-double-up"></i></a>

    <header class="header-section">
        <div>
            <div class="container">
                <div class="row d-flex header-area">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url "core:index" %}">
                            <img src="{% static 'assets/images/logo.png' %}" class="logo" alt="Payestiflogo">
                        </a>
                        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbar-content">
                            <i class="fa-solid fa-bars"></i>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbar-content">
                            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                                {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="{% url "account:account" %}">Account</a>
                                    {% comment %} <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Freelancer Payments</a></li>
                                        <li><a class="nav-link" href="subscriptions.html">Subscriptions</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul> {% endcomment %}
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="{% url "account:kyc-reg" %}">Profile</a>
                                    {% comment %} <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="payments-01.html">Business Payments</a></li>
                                        <li><a class="nav-link" href="business-account.html">Business Account</a></li>
                                        <li><a class="nav-link" href="corporate-card.html">Corporate Card</a></li>
                                        <li><a class="nav-link" href="expense-management.html">Expense Management</a></li>
                                        <li><a class="nav-link" href="budgeting-and-analytics.html">Budgeting</a></li>
                                        <li><a class="nav-link" href="integrations.html">Integrations</a></li>
                                        <li><a class="nav-link" href="invoice-management.html">Invoice</a></li>
                                        <li><a class="nav-link" href="security.html">Security</a></li>
                                        <li><a class="nav-link" href="rewards.html">Rewards</a></li>
                                        <li><a class="nav-link" href="fees.html">Fees</a></li>
                                    </ul> {% endcomment %}
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="{% url "core:transaction-list" %}">View Transactions</a>
                                    {% comment %} <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="about-us.html">About Us</a></li>
                                        <li><a class="nav-link" href="career.html">Career</a></li>
                                        <li><a class="nav-link" href="career-details.html">Career Details</a></li>
                                        <li class="dropend sub-navbar">
                                            <a href="javascript:void(0)" class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                              data-bs-auto-close="outside">Blog</a>
                                            <ul class="dropdown-menu sub-menu shadow">
                                                <li><a class="nav-link" href="blog.html">Blog</a></li>
                                                <li><a class="nav-link" href="blog-details.html">Blog Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a class="nav-link" href="error.html">Error</a></li>
                                    </ul> {% endcomment %}
                                </li>
                                <li class="nav-item dropdown main-navbar">
                                    <a class="nav-link dropdown-toggle" href="{% url "core:search-user"  %}">User Search</a>
                                    {% comment %} <ul class="dropdown-menu main-menu shadow">
                                        <li><a class="nav-link" href="help-center.html">Help Center</a></li>
                                        <li><a class="nav-link" href="help-center-category.html">Help Category</a></li>
                                    </ul> {% endcomment %}
                                </li>
                                {% endif %}
                            </ul>
                            <div class="right-area header-action d-flex align-items-center max-un">
                                {% if request.user.is_authenticated %}
                                  {% if request.user.is_staff %}
                                        <a href="/admin" class="login cmdn-btn">Admin</a>
                                   {% endif %}
                                <a href="{% url 'userauth:signout' %}" class="login cmn-btn">Sign Out</a>
                                {% else %}
                                <a href="{% url 'userauth:signin' %}" class="login">Login</a>
                                <a href="{% url 'userauth:signup' %}" class="cmn-btn">Sign Up
                                    <i class="fas fa-caret-right"></i>
                                </a>
                                {% endif %}
                                
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- alert start -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script> 
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 4000)
                </script>
                <!-- alert end -->
            </div>
        </div>
    </header>
    <!-- header-section end -->

{% block content %}
  
{% endblock content %}


    
    <!--==================================================================-->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>