core/urls.py
from django.urls import path
from . import views
from . import transfer
from . import transaction
from . import payment_requst
from . import credit_card

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('searchuser/', transfer.search_user_with_account_number, name="search-user"),
    path('amount-transfer/<accountNumber>/', transfer.AmonutTransfer, name="transfer"),
    path('amount-transfer-process/<account_number>/', transfer.AmountTransferProcess, name="transferprocess"),
    path('transfer-confirmation/<accountnumber>/<transaction_id>/', transfer.Transaction_confirmation, name="transferconfirmation"),
    path('transfer-completion-process/<accountnumber>/<transaction_id>/', transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<accountnumber>/<transaction_id>/", transfer.transfer_completed, name='transfer-completed'),
    path('transaction-list/', transaction.transaction_list, name="transaction-list"),
    path('transaction-detail/<transaction_id>/', transaction.transaction_detail, name="transaction-detail"),
    path('searchuserrequest/', payment_requst.searchUserRequest, name="searchuserrequest"),
    path("payment-request/<accountNumber>/", payment_requst.amountRequest, name="paymentrequest"),
    path('amount-request-process/<accountNumber>/', payment_requst.amountRequestProcess, name='amountrequestprocess'),
    path('request_confirmation/<accountNumber>/<transaction_id>/', payment_requst.requestConfirmation, name="requestconfirmation"),
    path('request_final_confirmation/<accountNumber>/<transaction_id>/', payment_requst.amoutnRequestFinalProcess, name="requestfinalconfirmation"),
    path('request-completed/<accountNumber>/<transaction_id>/', payment_requst.requestComplted, name='requestcompleted'),
    path('settlement_confirmation/<accountNumber>/<transaction_id>/', payment_requst.settlement_confirmation, name="settlementconfirmation"),
    path('settlementprocessing/<accountNumber>/<transaction_id>/', payment_requst.settlement_processing, name="settlementprocessing"),
    path('settlement-completed/<accountNumber>/<transaction_id>/', payment_requst.settlement_completed, name="settlementcompletd"),
    path('delete-request/<accountNumber>/<transaction_id>/', payment_requst.request_delete, name="requestdelete"),
    path('card/<card_id>/', credit_card.card_detail, name="creditcarddetail"),
    path('fundingcard/<card_id>/', credit_card.fund_credit_card, name="fundcreditcard"),
    path('withdrawfund/<card_id>/', credit_card.withdraw_fund, name="withdrawfund"),
    path("delete-credit-card/<card_id>/", credit_card.delete_card, name="deletecreditcard"),
    path('recipients/', transaction.recipient_list, name="recipients")

]

paymentProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('users/', include("userauth.urls")),
    path('account/', include("account.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/transfer/transfer-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}


{% block content %}


    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static "assets/images/icon/support-icon.png" %}" alt="icon">
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static "assets/images/icon/submitted-icon.png" %}" alt="icon">
                            </div>
                            <h3>Submitted</h3>
                            <p>Payment request {{transaction.transaction_id}} was sent to {{account.user.kyc.fullname}}</p>
                            <h5>Manage payment request | Request another Payment</h5>
                        </div>
                        <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static "assets/images/icon/whatsapp.png" %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static "assets/images/icon/skype.png" %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static "assets/images/icon/messenger.png" %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static "assets/images/icon/copy-link.png" %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/transfer/transfer-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}

{% block content %}

<section class="dashboard-section body-collapse pay step step-2 step-3">
    <div class="overlay pt-120">
        <div class="container-fruid">
            <div class="main-content">
                <div class="head-area d-flex align-items-center justify-content-between">
                    <h4>Make a Payment</h4>
                    <div class="icon-area">
                        <img src="assets/images/icon/support-icon.png" alt="icon">
                    </div>
                </div>
                <div class="choose-recipient">
                    <div class="step-area">
                       
                        <h5>Confirm Your Transfer</h5>
                    </div>
                    <div class="user-select">
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <img src="{{account.user.kyc.image.url}}" style="height:75px; width:75px; border-radius:50%; object-fit:cover;" alt="image">
                                </div>
                                <div class="text-area">
                                    <p>To: {{account.user.kyc.fullname}}</p>
                                    <span class="mdr"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="541c312639353a6761143339353d387a373b39">{{account.kyc.email}}</a></span>
                                </div>
                            </div>
                            <div class="right">
                                {% comment %} <a href="javascript:void(0)">
                                    <i class="icon-g-tick"></i>
                                    Choose
                                </a>
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a> {% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="payment-details">
                    <div class="top-area">
                        <h6>Payment Details</h6>
                        <div class="right">
                            <a href="{% url "core:transfer" account.account_number %}">
                                <i class="icon-h-edit"></i>
                                Edit
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <ul class="details-list">
                                <li>
                                    <span>You Send</span>
                                    <b>{{transaction.amount}}</b>
                                </li>
                                <li>
                                    <span>Recipient gets</span>
                                    <b>{{transaction.amount}}</b>
                                </li>
                                <li>
                                    <span>E-mail of receiver</span>
                                    <b><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="d3bebca1a1baa0e1e193b4beb2babffdb0bcbe">{{account.user.email}}</a></b>
                                </li>
                                <li>
                                    <span>Fee</span>
                                    <b>Free</b>
                                </li>
                                <li>
                                    <span>Purpose</span>
                                    <b>{{transaction.description}}</b>
                                </li>
                                <li>
                                    <span>Transfer will be receive on </span>
                                    <b>{{transaction.date}}</b>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <form action="#">
                    <div class="checkbox">
                        <input type="checkbox" id="confirm">
                        <label for="confirm">I confirm the payment details above</label>
                    </div>
                    <div class="footer-area mt-40">
                        {% comment %} <a href="pay-step-2.html">Previous Step</a> {% endcomment %}
                        <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Transfer</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- Dashboard Section end -->

<!-- Transfer Popup start -->
<div class="transfer-popup">
    <div class="container-fruid">
        <div class="row">
            <div class="col-lg-6">
                <div class="modal fade" id="transferMod" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <ul class="nav nav-tabs d-none" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                <div class="modal-content">
                                    <div class="modal-header mb-60 justify-content-between">
                                        <a href="javascript:void(0)">
                                            <i class="icon-a-left-arrow"></i>
                                            Back
                                        </a>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                    </div>
                                    <div class="main-content">
                                        <h4>Confirm Transfer!</h4>
                                        <p>We have sent a verification code on your phone + Number +44831***932. Please enter verification code below</p>
                                        <form action="{% url "core:transfer-process" account.account_number transaction.transaction_id %}" method="POST">
                                            {% csrf_token %}
                                            {{ account.account_number }}
                                            {{ transaction.transaction_id }}
                                            <div class="userInput">
                                                <input minlength=4 maxlength=4 type="text" name="pin_number">
                                            </div>
                                            <a href="javascript:void(0)">Don’t receive a code?</a>
                                            <button type="submit" class="mt-60 confirm">Confirm</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                    </div>
                                    <div class="main-content text-center pt-120 pb-120">
                                        <img src="assets/images/icon/success.png" alt="icon">
                                        <h3>Success</h3>
                                        <p>Transfer was completed.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Transfer Popup start -->



{% endblock content %}

templates/transfer/transfer_amout.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% block content %}


    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static "assets/images/icon/support-icon.png" %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{account.user.kyc.image.url}}" style="height:75px; width:75px; border-radius:50%; object-fit:cover;" alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{account.user.kyc.fullname}}</p>
                                        <p>{{account.account_number}}</p>
                                        <span class="mdr"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="82cae7f0efe3ecb1b7c2e5efe3ebeeace1edef">{{account.user.email}}</a></span>
                                    </div>
                                </div>
                                <div class="right">
                                    {% comment %} <a href="javascript:void(0)">
                                        <i class="icon-g-tick"></i>
                                        Choose
                                    </a> {% endcomment %}
                                    {% comment %} <a href="{% url "core:search-user"%}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a> {% endcomment %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url "core:transferprocess" account.account_number %}" method="POST" >
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input name="amount-send" class="xxlr" onkeyup="CalculateBalance()" placeholder="{{request.user.account.account_balance|intcomma}}" type="number" id="amount-send">
                                
                                <span>ETB</span>
                            </div>
                            <p>Available Balance<b>{{request.user.account.account_balance}}</b></p>
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Description</span>
                            <div class="input-area">
                                <input name="description" class="xxlr"  placeholder="Enter a dscription" type="text" id="amount-send">
                                
                            </div>
                            
                        </div>
                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{ request.user.account.account_balance }}"
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount-send")
                                let sendAmount = sendAmount_input.value
                                let errorDiv = document.getElementById("error-div")
                                let total_to_pay = document.getElementById("total-to-pay")
                                
                                let errors = []
                                new_bal = available_balance - sendAmount
                                console.log(new_bal)
                                new_balance.innerHTML = `New Balance <b> ${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}</b>`
                                total_to_pay.innerHTML = `BIRR <b> ${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}</b>`
                            
                                if (new_bal < 0){
                                    new_balance.style.color ="red"
                                    alert("You can only send " + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                                
                                } else {
                                    new_balance.style.color= "#27276e"
                                }
                            }
                        </script>
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li>
                                <h5>Total To Pay</h5>
                            </li>
                            <li>
                                <h5 id="total-to-pay">400.00 USD</h5>
                            </li>
                        </ul>
                        <div class="footer-area mt-40">
                            {% comment %} <a href="pay-step-1.html">Previous Step</a> {% endcomment %}
                            <button type="submit" style="padding: 10px 30px; border-radius:20px;" class="active">Proceed to the next stage</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}