core/urls.py
from django.urls import path
from . import views
from . import transfer
from . import transaction
from . import payment_requst
from . import credit_card

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('searchuser/', transfer.search_user_with_account_number, name="search-user"),
    path('amount-transfer/<accountNumber>/', transfer.AmonutTransfer, name="transfer"),
    path('amount-transfer-process/<account_number>/', transfer.AmountTransferProcess, name="transferprocess"),
    path('transfer-confirmation/<accountnumber>/<transaction_id>/', transfer.Transaction_confirmation, name="transferconfirmation"),
    path('transfer-completion-process/<accountnumber>/<transaction_id>/', transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<accountnumber>/<transaction_id>/", transfer.transfer_completed, name='transfer-completed'),
    path('transaction-list/', transaction.transaction_list, name="transaction-list"),
    path('transaction-detail/<transaction_id>/', transaction.transaction_detail, name="transaction-detail"),
    path('searchuserrequest/', payment_requst.searchUserRequest, name="searchuserrequest"),
    path("payment-request/<accountNumber>/", payment_requst.amountRequest, name="paymentrequest"),
    path('amount-request-process/<accountNumber>/', payment_requst.amountRequestProcess, name='amountrequestprocess'),
    path('request_confirmation/<accountNumber>/<transaction_id>/', payment_requst.requestConfirmation, name="requestconfirmation"),
    path('request_final_confirmation/<accountNumber>/<transaction_id>/', payment_requst.amoutnRequestFinalProcess, name="requestfinalconfirmation"),
    path('request-completed/<accountNumber>/<transaction_id>/', payment_requst.requestComplted, name='requestcompleted'),
    path('settlement_confirmation/<accountNumber>/<transaction_id>/', payment_requst.settlement_confirmation, name="settlementconfirmation"),
    path('settlementprocessing/<accountNumber>/<transaction_id>/', payment_requst.settlement_processing, name="settlementprocessing"),
    path('settlement-completed/<accountNumber>/<transaction_id>/', payment_requst.settlement_completed, name="settlementcompletd"),
    path('delete-request/<accountNumber>/<transaction_id>/', payment_requst.request_delete, name="requestdelete"),
    path('card/<card_id>/', credit_card.card_detail, name="creditcarddetail"),
    path('fundingcard/<card_id>/', credit_card.fund_credit_card, name="fundcreditcard"),
    path('withdrawfund/<card_id>/', credit_card.withdraw_fund, name="withdrawfund"),
    path("delete-credit-card/<card_id>/", credit_card.delete_card, name="deletecreditcard"),
    path('recipients/', transaction.recipient_list, name="recipients")

]

paymentProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('users/', include("userauth.urls")),
    path('account/', include("account.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/transaction/recipients.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% block content %}

<!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="row">
                    <div class="col-xl-12 col-lg-12">
                        <div class="section-content">
                            
                            <div class="transactions-area">
                                <div class="section-text">
                                    <h5>Recipients</h5>
                                    <p>Updated every several minutes</p>
                                </div>
                                <div class="top-area d-flex align-items-center justify-content-between">
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="upcoming-tab" data-bs-toggle="tab" data-bs-target="#upcoming" type="button" role="tab" aria-controls="upcoming" aria-selected="false">Received Transfer</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="receivedrequest-tab" data-bs-toggle="tab" data-bs-target="#receivedrequest" type="button" role="tab" aria-controls="upcoming" aria-selected="false">Received Requests</button>
                                        </li>
                                        
                                    </ul>
                                    <div class="view-all d-flex align-items-center">
                                        <a href="javascript:void(0)">View All</a>
                                        <img src="{% static 'assets1/images/icon/right-arrow.png' %}" alt="icon">
                                    </div>
                                </div>
                             
                                <div class="tab-content mt-40">
                                    <div class="tab-pane fade show active" id="latest" role="tabpanel" aria-labelledby="latest-tab">
                                        <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">Name/ Business</th>
                                                        <th scope="col">Date</th>
                                                        <th scope="col">Status</th>
                                                        <th scope="col">Amount</th>
                                                        <th scope="col">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                    {% for s in reciver_transaction %}
                                                        <tr data-bs-toggle="modal" data-bs-target="#transactionsMod">
                                                            <th scope="row">
                                                                <p>{{s.sender.kyc.fullname}}</p>
                                                                <p class="mdr">{{s.transaction_type|title}}</p>
                                                            </th>
                                                            <td>
                                                                <p><small>{{s.date|date:"h:s"}}</small></p>
                                                                <p class="mdr">{{s.date|date:"d:m:y"}}</p>
                                                            </td>
                                                            <td>
                                                                {% if s.status == 'complete' %} 
                                                                    <p class="text-success">{{s.status|title}}</p>
                                                                    {% endif %}
                                                                    {% if s.status == 'processing' %}
                                                                    <p class="inprogress">{{s.status|title}}</p>
                                                                    {% endif %}
                                                                    {% if s.status == 'pending' %}
                                                                    <p class="inprogress">{{s.status|title}}</p>
                                                                    {% endif %}
                                                                    {% if s.status == 'failed' %}
                                                                    <p class="text-danger">{{s.status|title}}</p>
                                                                 {% endif %}       
                                                                </td>
                                                            <td>
                                                                <p>{{s.amount}}</p>
                                                            </td>
                                                            <td>
                                                                <a href="{% url "core:transaction-detail" s.transaction_id %}" class=""><i class="fas fa-eye"></i></a>

                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                      
                                    <div class="tab-pane fade" id="receivedrequest" role="tabpanel" aria-labelledby="receivedrequest-tab">
                                        <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">Name/ Business What</th>
                                                        <th scope="col">Date</th>
                                                        <th scope="col">Status</th>
                                                        <th scope="col">Amount</th>
                                                        <th scope="col">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                    {% for r in reciver_request_transaction %}
                                                    <tr data-bs-toggle="modal" data-bs-target="#transactionsMod">
                                                        <th scope="row">
                                                            <p>{{r.sender.kyc.fullname}}</p>
                                                            <p class="mdr">{{r.transaction_type|title}}</p>
                                                        </th>
                                                        <td>
                                                            <p><small>{{r.date|date:"h:s"}}</small></p>
                                                            <p class="mdr">{{r.date|date:"d:m:y"}}</p>
                                                        </td>
                                                        <td>
                                                                {% if r.status == 'complete' %} 
                                                                <p class="text-success">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'processing' %}
                                                                <p class="inprogress">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'pending' %}
                                                                <p class="inprogress">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'failed' %}
                                                                <p class="text-danger">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'request_sent' %} 
                                                                <p class="text-success">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'request_settled' %}
                                                                <p class="text-success">{{r.status|title}}</p>
                                                                {% endif %}
                                                                {% if r.status == 'request_processing' %}
                                                                <p class="inprogress">{{r.status|title}}</p>
                                                                {% endif %}
                                                             {% comment %} {% endif %}        {% endcomment %}
                                                            </td>
                                                        <td>
                                                            <p>{{r.amount}}</p>
                                                        </td>
                                                        {% if r.status == "request_settled" %}
                                                        <td>
                                                        <a href="{% url "core:transaction-detail" r.transaction_id %}" class="btn btn-success"><i class="fas fa-eye"></i> Settled</a>
                                                        </td>
                                                        {% comment %} <a href="{% url "core:transaction-detail" r.transaction_id %}" class="btn btn-danger"><i class="fas fa-x"></i> Delete</a> {% endcomment %}
                                                        {% endif %}
                                                        {% if r.status == "request_processing" or r.transaction == "request_sent" %}
                                                        <td>
                                                        <a href="{% url "core:transaction-detail" r.transaction_id %}" class="btn btn-primary"><i class="fas fa-eye"></i> View</a>
                                                        <a href="{% url "core:requestdelete" r.reciver.account.account_number r.transaction_id %}" class="btn btn-danger"><i class="fas fa-x"></i> Delete</a>
                                                    </td>
                                                        {% endif %}
                                                        {% empty%}
                                                        <li>No recived Transaction</li>
                                                    </tr>
                                                {% endfor %}

                                               
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>                        
        {% endblock %}

templates/transaction/transaction-detail.html
{% extends 'partials/dashboard-base.html' %}
{% load static %}
{% block content  %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="row">
                    <div class="col-xl-11 col-lg-11">
                        <div class="section-content">

                            <div class="transactions-popup">
                                <div class="container-fruid">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div>
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-header justify-content-between">
                                                            <h5>Transaction Details</h5>
                                                            <a href="{% url 'core:transaction-list' %}"><i class="material-symbols-outlined">Back</i></a>
                                                        </div>
                                                        <div class="main-content">
                                                            <div class="row">
                                                                <div class="col-sm-5 text-center">
                                                                    <div class="icon-area">
                                                                        <img style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover;" src="{{transaction.sender.kyc.image.url}}" alt="icon"> 
                                                                    </div>
                                                                    <div class="text-area">
                                                                        <h6>Sender: {{transaction.sender.kyc.fullname|title}}</h6>                                    {% comment %} <h6 class="mt-2">Reciever: {{transaction.reciever.kyc.full_name|title}}</h6> --> {% endcomment %}
                                                                        <h5><b>{{transaction.amount|intcomma}} USD</b></h5>
                                                                        <p>{{transaction.date}}</p>
                                                                        <!-- <p class="text-warning com ">{{transaction.status|title}}</p> -->
                                                                        {% if transaction.status == 'completed' %}
                                                                            <p class="text-success">{{transaction.status|title}}</p>
                                                                        {% endif %}
                                                                        {% if transaction.status == 'pending' %}
                                                                            <p class="text-warning">{{transaction.status|title}}</p>
                                                                        {% endif %}
                                                                        {% if transaction.status == 'failed' %}
                                                                            <p class="danger">{{transaction.status|title}}</p>
                                                                        {% endif %}
                                                                        {% if transaction.status == 'processing' %}
                                                                            <p class="text-warning">{{transaction.status|title}}</p>
                                                                        {% endif %}
                                                                    </div>
                                                                </div>
                                                                <div class="col-sm-7">
                                                                    <div class="right-area">
                                                                        <h6>Transaction Details</h6>
                                                                        <ul class="payment-details">
                                                                            <li>
                                                                                <span>Payment Amount</span>
                                                                                <span>{{transaction.amount|intcomma}} USD</span>
                                                                            </li>
                                                                            <li>
                                                                                <span>Fee</span>
                                                                                <span>Free USD</span>
                                                                            </li>
                                                                            <li>
                                                                                <span>Total Amount</span>
                                                                                <span>{{transaction.amount|intcomma}} USD</span>
                                                                            </li>
                                                                        </ul>
                                                                        <ul class="payment-info">
                                                                            <li>
                                                                                <p>Payment From</p>
                                                                                <span class="mdr">{{transaction.sender.kyc.fullname|title}}</span>
                                                                            </li>
                                                                            <li>
                                                                                <p>Payment To</p>
                                                                                <span class="mdr">{{transaction.reciver.kyc.fullname|title}}</span>
                                                                            </li>
                                                                            <li>
                                                                                <p>Payment Description</p>
                                                                                <span class="mdr">{{transaction.description}}</span>
                                                                            </li>
                                                                            <li>
                                                                                <p>Transaction ID:</p>
                                                                                <span class="mdr">{{transaction.transaction_id}}</span>
                                                                            </li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}